# Generated by Django 5.0.3 on 2024-03-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0010_alter_vencimiento_options_and_more'),
        ('persona', '0002_alter_persona_domicilio_alter_persona_localidad_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona'),
        ),
    ]
