# Generated by Django 3.2.4 on 2022-04-25 15:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PA', 'Pais'), ('PR', 'Provincia'), ('DE', 'Departamento'), ('MU', 'Municipio'), ('LO', 'Localidad'), ('BA', 'Barrio')], default='LO', max_length=2)),
                ('nombre', models.CharField(help_text='Ejemplo: SAN ISIDRO', max_length=100, verbose_name='Nombre')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Ejemplo: VALLE VIEJO', null=True, on_delete=django.db.models.deletion.CASCADE, to='util.ubicacion', verbose_name='Ubicación Padre')),
            ],
            options={
                'verbose_name': 'Ubicación ',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('celu', 'Celular'), ('fijo', 'Teléfono de Linea'), ('wsp', 'Whatsapp')], default='fijo', max_length=4, verbose_name='Tipo de teléfono')),
                ('contact_point', models.CharField(max_length=40, verbose_name='Número')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_social', models.CharField(choices=[('fbk', 'Facebook'), ('insta', 'Instagram'), ('lnkd', 'Linkedin'), ('twt', 'Twitter'), ('wsp', 'WhatsApp'), ('ytb', 'YouTube'), ('snap', 'Snapchat'), ('g+', 'Google+'), ('pin', 'Pinterest')], max_length=5, verbose_name='Red Social')),
                ('url', models.URLField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reserva', 'Reserva'), ('consulta', 'Consulta'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], default='consulta', max_length=10, verbose_name='Tipo de teléfono')),
                ('contact_point', models.EmailField(max_length=40, verbose_name='Correo Electrónico')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Correo electrónico',
                'verbose_name_plural': 'Correos electrónicos',
            },
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('nombre', 'parent'), name='unique_ubicacion'),
        ),
    ]
