# Generated by Django 5.0.3 on 2024-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], default='consulta', max_length=10, verbose_name='Tipo de teléfono'),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='red_social',
            field=models.CharField(choices=[('fbk', 'Facebook'), ('insta', 'Instagram'), ('lnkd', 'Linkedin'), ('twt', 'Twitter'), ('wsp', 'WhatsApp'), ('ytb', 'YouTube'), ('snap', 'Snapchat'), ('tkt', 'TikTok'), ('pin', 'Pinterest')], max_length=5, verbose_name='Red Social'),
        ),
    ]
