# Generated by Django 5.0.3 on 2024-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_alter_mail_type_alter_redsocial_red_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='red_social',
            field=models.CharField(choices=[('fbk', 'Facebook'), ('insta', 'Instagram'), ('lnkd', 'Linkedin'), ('twt', 'Twitter/X'), ('wsp', 'WhatsApp'), ('ytb', 'YouTube'), ('snap', 'Snapchat'), ('tiktok', 'TikTok'), ('pin', 'Pinterest')], max_length=6, verbose_name='Red Social'),
        ),
    ]
