# Generated by Django 5.0.3 on 2024-03-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('documento_identidad', models.CharField(max_length=12, unique=True, verbose_name='Documento Identidad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('cuit', models.CharField(max_length=15, unique=True, verbose_name='CUIL/CUIT')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_localidad', to='util.ubicacion')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nacionalidad', to='util.ubicacion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-id'],
            },
        ),
    ]
