# Generated by Django 5.0.3 on 2024-03-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_localidad', to='util.ubicacion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nacionalidad', to='util.ubicacion'),
        ),
    ]
